---
- name: Update Windows Server
  hosts: windows_servers
  gather_facts: no

  tasks:
    - name: Check for updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: searched
      register: update_result

    - name: Print update information
      debug:
        var: update_result

    - name: Install updates if found
      ansible.windows.win_updates:
        state: installed
      when: update_result.found_update_count > 0
